### PR TITLE
Bumped to API 3.0.0 + Add/Changes some codes.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jackthehack21** [comment]
How can you bump to 3.0.0 when it’s already at ALPHA 12 ?

**Comment by JaxkDev** [comment]
Overall I’m very hesitant to merge this because it does break a few poggit PQRS rules and will not pass to a update and,
We’re re doing the commands in the devs branch
I’ve asked @YassenTrick to review then we’ll decide.

**Review by JaxkDev — COMMENTED** [review]
Changes made are essential for PQRS and stability

**Comment by JaxkDev** [comment]
Merged after some edits.

**Pull request merged**
